services:
  # Frontend service
  budget-manager-front:
    container_name: frontend
    image: frontend:0.1.0
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
    networks:
      - common
# Backend service
  budget-manager-back:
    container_name: backend
    image: backend:0.1.0
    ports:
      - 4000:4000
    environment:
      - PORT=4000 
      - DBUSER=postgres 
      - DBPASS=mypass 
      - DBHOST=192.168.16.4
      - DBPORT=5432 
      - DBNAME=postgres 
      - SECRET_JWT_SEED=lAs_ros@s_son_RoJas_Y_m@x_es_n@gro
    networks:
      - common
# Database service
  postgres:
    container_name: postgres
    image: postgres:14.5
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=mypass
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - PGDATA:/var/lib/postgresql/data
      - ./budget-manager-database/db:/docker-entrypoint-initdb.d
    networks:
      - common
volumes:
  PGDATA:
networks:
  common:
