
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-manager-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-manager-back
  template:
    metadata:
      labels:
        app: budget-manager-back
    spec:
      containers:
      - name: budget-manager-back
        image: marcelaobeso/budget-back:0.1.2
        env:
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: pg-secrets-ag
                key: DBPASS
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: pg-secrets-ag
                key: PORT
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: pg-secrets-ag
                key: DBUSER
          - name: DBPORT
            valueFrom:
              secretKeyRef:
                name: pg-secrets-ag
                key: DBPORT
          - name: DBNAME
            valueFrom:
              secretKeyRef:
                name: pg-secrets-ag
                key: DBNAME
          - name: SECRET_JWT_SEED
            valueFrom:
              secretKeyRef:
                name: pg-secrets-ag
                key: SECRET_JWT_SEED
          - name: DBHOST
            value: pg-service
        resources:
          limits:
            memory: "256Mi"
            cpu: "256m"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  type: LoadBalancer
  selector:
    app: budget-manager-back
  ports:
  - port: 4000
    targetPort: 4000