apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-manager-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-manager-front
  template:
    metadata:
      labels:
        app: budget-manager-front
    spec:
      containers:
      - name: budget-manager-front
        image: susguzman/w2-frotend:0.1.0-alpine-gcp
        resources:
          limits:
            memory: "256Mi"
            cpu: "256m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: LoadBalancer
  selector:
    app: budget-manager-front
  ports:
  - port: 8080
    targetPort: 80